# Generated by Django 2.0.6 on 2018-07-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20180704_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='had_been_registered',
        ),
    ]
