# Generated by Django 2.0.6 on 2018-06-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='total_product',
            new_name='total_products',
        ),
    ]
